# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1100, 350)
        Dialog.setStyleSheet("background-color: rgb(245, 245, 175)")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 1081, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 79, 521, 201))
        self.tableWidget.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.to_add_shop = QtWidgets.QPushButton(Dialog)
        self.to_add_shop.setGeometry(QtCore.QRect(10, 300, 81, 31))
        self.to_add_shop.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.to_add_shop.setObjectName("to_add_shop")
        self.to_delete_shop = QtWidgets.QPushButton(Dialog)
        self.to_delete_shop.setGeometry(QtCore.QRect(100, 300, 81, 31))
        self.to_delete_shop.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.to_delete_shop.setObjectName("to_delete_shop")
        self.tableWidget_2 = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_2.setGeometry(QtCore.QRect(570, 79, 521, 201))
        self.tableWidget_2.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.to_add_pub = QtWidgets.QPushButton(Dialog)
        self.to_add_pub.setGeometry(QtCore.QRect(820, 300, 81, 31))
        self.to_add_pub.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.to_add_pub.setObjectName("to_add_pub")
        self.to_delete_pub = QtWidgets.QPushButton(Dialog)
        self.to_delete_pub.setGeometry(QtCore.QRect(910, 300, 81, 31))
        self.to_delete_pub.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.to_delete_pub.setObjectName("to_delete_pub")
        self.Update_shop = QtWidgets.QPushButton(Dialog)
        self.Update_shop.setGeometry(QtCore.QRect(190, 300, 81, 30))
        self.Update_shop.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Update_shop.setObjectName("Update_shop")
        self.Update_pub = QtWidgets.QPushButton(Dialog)
        self.Update_pub.setGeometry(QtCore.QRect(1000, 300, 81, 30))
        self.Update_pub.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Update_pub.setObjectName("Update_pub")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(570, 40, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.to_add_shop.setText(_translate("Dialog", "Добавить"))
        self.to_delete_shop.setText(_translate("Dialog", "Удалить"))
        self.to_add_pub.setText(_translate("Dialog", "Добавить"))
        self.to_delete_pub.setText(_translate("Dialog", "Удалить"))
        self.Update_shop.setText(_translate("Dialog", "Обновить"))
        self.Update_pub.setText(_translate("Dialog", "Обновить"))
        self.label_3.setText(_translate("Dialog", "Менеджеры магазина"))
        self.label_4.setText(_translate("Dialog", "Менеджеры издательства"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
