# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'publish_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1100, 380)
        Dialog.setStyleSheet("background-color: rgb(245, 245, 175)")
        self.auth_as = QtWidgets.QLabel(Dialog)
        self.auth_as.setGeometry(QtCore.QRect(10, 10, 1081, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.auth_as.setFont(font)
        self.auth_as.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.auth_as.setText("")
        self.auth_as.setAlignment(QtCore.Qt.AlignCenter)
        self.auth_as.setObjectName("auth_as")
        self.Change_book = QtWidgets.QPushButton(Dialog)
        self.Change_book.setGeometry(QtCore.QRect(100, 330, 81, 30))
        self.Change_book.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Change_book.setObjectName("Change_book")
        self.Add_book = QtWidgets.QPushButton(Dialog)
        self.Add_book.setGeometry(QtCore.QRect(10, 330, 81, 30))
        self.Add_book.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Add_book.setObjectName("Add_book")
        self.tableWidget_3 = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 130, 530, 192))
        self.tableWidget_3.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.Add_author = QtWidgets.QPushButton(Dialog)
        self.Add_author.setGeometry(QtCore.QRect(830, 330, 81, 30))
        self.Add_author.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Add_author.setObjectName("Add_author")
        self.Change_author = QtWidgets.QPushButton(Dialog)
        self.Change_author.setGeometry(QtCore.QRect(920, 330, 81, 30))
        self.Change_author.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Change_author.setObjectName("Change_author")
        self.tableWidget_2 = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_2.setGeometry(QtCore.QRect(560, 130, 530, 192))
        self.tableWidget_2.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(560, 70, 521, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 531, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.Update_book = QtWidgets.QPushButton(Dialog)
        self.Update_book.setGeometry(QtCore.QRect(190, 330, 81, 30))
        self.Update_book.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Update_book.setObjectName("Update_book")
        self.Update_author = QtWidgets.QPushButton(Dialog)
        self.Update_author.setGeometry(QtCore.QRect(1010, 330, 81, 30))
        self.Update_author.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Update_author.setObjectName("Update_author")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Change_book.setText(_translate("Dialog", "Изменить"))
        self.Add_book.setText(_translate("Dialog", "Добавить"))
        self.Add_author.setText(_translate("Dialog", "Добавить"))
        self.Change_author.setText(_translate("Dialog", "Изменить"))
        self.label_3.setText(_translate("Dialog", "Авторы"))
        self.label_4.setText(_translate("Dialog", "Книги"))
        self.Update_book.setText(_translate("Dialog", "Обновить"))
        self.Update_author.setText(_translate("Dialog", "Обновить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
